<?php
/**
 * This file is part of the Deployer package.
 *
 * (c) Dries De Peuter <dries@nousefreak.be>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Deployer\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Dries De Peuter <dries@nousefreak.be>
 */
class QueueRepository extends EntityRepository
{
	public function getSortedQueue()
	{
		return $this->findBy(array(), array(
			'createdAt' => 'asc',
		));
	}
}
